[package]
name = "raven-railgun-testkit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
raven-railgun-core = { workspace = true }
raven-railgun-engine = { workspace = true }
raven-inspire = { workspace = true }
